// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJFjdg_8g5lx_-vifNIeNcHqBjGpd3kY',
    appId: '1:264083080056:web:402d123e64a79b8622fe8d',
    messagingSenderId: '264083080056',
    projectId: 'coffee-tracker-97eaf',
    authDomain: 'coffee-tracker-97eaf.firebaseapp.com',
    storageBucket: 'coffee-tracker-97eaf.appspot.com',
    measurementId: 'G-31TPK3GWFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdH65eyV_FtAqVvthwyex3X3YtP61x39s',
    appId: '1:264083080056:android:03a1fad3128fac9e22fe8d',
    messagingSenderId: '264083080056',
    projectId: 'coffee-tracker-97eaf',
    storageBucket: 'coffee-tracker-97eaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfNWIsbUYWD1GShBrEgfd6VfIttYPsGUs',
    appId: '1:264083080056:ios:83f4aadc60b1ade022fe8d',
    messagingSenderId: '264083080056',
    projectId: 'coffee-tracker-97eaf',
    storageBucket: 'coffee-tracker-97eaf.appspot.com',
    iosBundleId: 'com.example.coffeeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfNWIsbUYWD1GShBrEgfd6VfIttYPsGUs',
    appId: '1:264083080056:ios:83f4aadc60b1ade022fe8d',
    messagingSenderId: '264083080056',
    projectId: 'coffee-tracker-97eaf',
    storageBucket: 'coffee-tracker-97eaf.appspot.com',
    iosBundleId: 'com.example.coffeeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqJFjdg_8g5lx_-vifNIeNcHqBjGpd3kY',
    appId: '1:264083080056:web:edd98915b2ca902f22fe8d',
    messagingSenderId: '264083080056',
    projectId: 'coffee-tracker-97eaf',
    authDomain: 'coffee-tracker-97eaf.firebaseapp.com',
    storageBucket: 'coffee-tracker-97eaf.appspot.com',
    measurementId: 'G-X2HYL9084C',
  );
}
